### ISSUE TITLE
release an image based on minideb

### ISSUE THREAD

**Issue by jjo** [bitnami/bitnami-docker-thanos#2]
**Description**

There are some cases were we need some extra instrumentation to happen around thanos main container(s), then having only `scratch` images makes that cumbersome to tackle (copying `/bin/dash` binaries, or having to maintain own forked Dockerfile + images).

**Steps to reproduce the issue:**

Trying to use any "shell" CLI will fail with `scratch` image, for obvious reasons

**Additional information you deem important (e.g. issue happens only occasionally):**

Find below our actual example, where we instrument `thanos-storage-gateway` replicas to have their own serving "window" based on their replica number, by adapting the command `args` run for each different replica (something that's not natively supported by Kubernetes), highlights:

- initContainer run with `bitnami/minideb:buster` does the `args` blackmagic, creating a `/init/thanos-store.sh` script, as the main container entrypoint
- there the `copy_dash()` function copies  `/bin/dash` and needed `/lib64` libraries to another emptyDir, "just" to be able to run `/init/thanos-store.sh` script

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    name: thanos-store-gateway
  name: thanos-store-gateway
  namespace: thanos
spec:
  replicas: 1
  selector:
    matchLabels:
      name: thanos-store-gateway
      thanos-store-api: "true"
  serviceName: thanos-store-gateway
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: k8s-prometheus-role
        prometheus.io/scrape: "true"
      labels:
        name: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      containers:
      - args:
        - --block-sync-concurrency=2
        - --chunk-pool-size=250MB
        - --data-dir=/data
        - --index-cache-size=512MB
        - --log.level=debug
        - --objstore.config-file=/config/thanos.yaml
        command:
        - /init/thanos-store.sh
        env:
        - name: LD_LIBRARY_PATH
          value: /lib64
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: bitnami/thanos:0.14.0-scratch-r3
        imagePullPolicy: IfNotPresent
        name: thanos-store-gateway
        ports:
        - containerPort: 10901
          name: grpc-nometrics
        - containerPort: 10902
          name: http
        resources:
          limits:
            cpu: "2"
            memory: 15Gi
          requests:
            cpu: "1"
            memory: 6Gi
        stdin: false
        tty: false
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /init
          name: init
        - mountPath: /lib64
          name: lib64
        - mountPath: /config
          name: s3-config
      imagePullSecrets: []
      initContainers:
      - args: []
        command:
        - bash
        - -c
        - |
          get_times() {
              # Use number after '-' as factor, e.g. 'foo-bar-0' -> '0'
              typeset -i factor=${1/*-/}
              echo --min-time=-$((DAYS_OFFSET+DAYS_PER_POD*(factor+1)))d --max-time=-$((DAYS_OFFSET+DAYS_PER_POD*(factor)))d
          }
          # bitnami/thanos image is built `FROM scratch`, but we need
          # some `sh` to run /init/thanos-store.sh: copy dash and needed
          # libraries to `/lib64` shared emptyDir volume
          copy_dash() {
              cp -p /bin/dash /init/dash
              cp -p /lib/x86_64-linux-gnu/libc.so.6 /lib64-copy/libc.so.6
              cp -p /lib64/ld-linux-x86-64.so.2 /lib64-copy/ld-linux-x86-64.so.2
          }
          # Blow if any below envvar is unset
          : ${MY_POD_NAME:?} ${DAYS_PER_POD:?} ${DAYS_OFFSET:?}
          printf "#!/init/dash\nexec /thanos store $(get_times ${MY_POD_NAME}) \${@} \n" | install -m755 /dev/stdin /init/thanos-store.sh
          echo "INFO replica=${MY_POD_NAME} /init/thanos-store.sh:"
          cat /init/thanos-store.sh
          copy_dash
        env:
        - name: DAYS_OFFSET
          value: "21"
        - name: DAYS_PER_POD
          value: "14"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: bitnami/minideb:buster
        imagePullPolicy: IfNotPresent
        name: thanos-init
        ports: []
        resources:
          limits:
            cpu: "0.1"
            memory: 200Mi
          requests:
            cpu: "0.1"
            memory: 200Mi
        stdin: false
        tty: false
        volumeMounts:
        - mountPath: /init
          name: init
        - mountPath: /lib64-copy
          name: lib64
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: init
      - emptyDir: {}
        name: lib64
      - configMap:
          name: thanos-s3-config
        name: s3-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates: []
```
