### ISSUE TITLE
The ThanosRulerSpec from kube-prometheus prometheus-operator is not working with this image.

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/bitnami-docker-thanos#5]
**Description**

When you try to configure a ThanosRuler Specification for the prometheus-operator the container will stuck in CrashLoopbackOff, because /thanos/data is not possible to get mounted.

**Steps to reproduce the issue:**

1. Install Kube-prometheus Helm Chart
2. Configure the following ThanosRulerSpec
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  name: ruler
spec:
  image: docker.io/bitnami/thanos:0.23.1-scratch-r1
  replicas: 3
```
3. See Crashing containers.

**Describe the results you received:**

/thanos is a file because it is the binary.

/thanos/data is used by the operator to mount the tempdir for the thanos-ruler.

Those two are clashing.

https://quay.io/repository/thanos/thanos/manifest/sha256:2f7d1ddc7877b076efbc3fa626b5003f7f197efbd777cff0eec2b20c2cd68d20

Uses `/bin/thanos`

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
